services:
  db:
    image: couchdb
    container_name: couchdb
    restart: unless-stopped
    env_file:
      - couchdb.env
    ports:
      - 5984:5984
  shopping_cart:
    build: .
    container_name: shopping_cart
    restart: unless-stopped
    ports:
      - 8081:8081
